using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace ActivitySourceGenerator;

[Generator]
public class SimpleActivityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the ActivityAttribute
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "ActivityAttribute.g.cs", SourceText.From(ActivityAttributeSource, Encoding.UTF8)));

        // Find methods with ActivityAttribute
        var methodsProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ActivitySourceGenerator.Attributes.ActivityAttribute",
                static (node, _) => node is MethodDeclarationSyntax,
                static (ctx, _) => GetMethodInfo(ctx))
            .Where(static m => m != null)
            .Collect();

        // Generate activity wrappers
        context.RegisterSourceOutput(methodsProvider, static (spc, methods) => Execute(spc, methods));
    }

    private static MethodInfo GetMethodInfo(GeneratorAttributeSyntaxContext context)
    {
        var methodDeclaration = (MethodDeclarationSyntax)context.TargetNode;
        var methodSymbol = context.TargetSymbol as IMethodSymbol;
        
        if (methodSymbol == null)
            return null;

        var attributeData = context.Attributes.FirstOrDefault();
        
        return new MethodInfo(
            methodSymbol,
            methodDeclaration,
            attributeData);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<MethodInfo> methods)
    {
        if (methods.IsDefaultOrEmpty)
            return;

        var namespaces = methods.Select(m => m.Symbol.ContainingNamespace.ToDisplayString()).Distinct();
        var namespacesContent = string.Join("\n", namespaces.Select(ns => GenerateNamespace(ns, methods)));

        var sourceCode = 
            $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Diagnostics;
            using System.Threading.Tasks;

            {{namespacesContent}}
            """;

        context.AddSource("ActivityWrappers.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }

    private static string GenerateNamespace(string namespaceName, ImmutableArray<MethodInfo> methods)
    {
        var methodsInNamespace = methods.Where(m => m.Symbol.ContainingNamespace.ToDisplayString() == namespaceName);
        var classesContent = string.Join("\n", methodsInNamespace.GroupBy(m => m.Symbol.ContainingType.Name)
            .Select(group => GenerateActivityWrapperClass(group.Key, group.ToList())));

        return 
            $$"""
            namespace {{namespaceName}};
            
            {{classesContent}}
            
            """;
    }

    private static string GenerateActivityWrapperClass(string className, List<MethodInfo> methods)
    {
        var methodsContent = string.Join("\n", methods.Select(GenerateActivityWrapperMethod));

        return 
            $$"""
            public static class {{className}}ActivityWrapper
            {
                private static readonly ActivitySource _activitySource = new("{{className}}");

            {{methodsContent}}
            }
            """;
    }

    private static string GenerateActivityWrapperMethod(MethodInfo methodInfo)
    {
        var method = methodInfo.Symbol;
        var isAsync = method.IsAsync;
        var returnType = method.ReturnType.ToDisplayString();
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
        var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));

        var activityName = GetActivityName(methodInfo.AttributeData, method);
        var wrapperMethodName = $"{method.Name}WithActivity";

        var methodBody = isAsync 
            ? GenerateAsyncWrapperBody(method, activityName, arguments)
            : GenerateSyncWrapperBody(method, activityName, arguments);

        var asyncKeyword = isAsync ? "async " : "";

        return 
            $$"""
                /// <summary>
                /// Wrapper for {{method.ContainingType.Name}}.{{method.Name}} with automatic activity tracing
                /// </summary>
                public static {{asyncKeyword}}{{returnType}} {{wrapperMethodName}}({{parameters}})
                {
            {{methodBody}}
                }

            """;
    }

    private static string GenerateSyncWrapperBody(IMethodSymbol method, string activityName, string arguments)
    {
        var hasReturnValue = !method.ReturnsVoid;
        var containingTypeDisplay = method.ContainingType.ToDisplayString();

        if (hasReturnValue)
        {
            return 
            $$"""
                    using var activity = _activitySource.StartActivity("{{activityName}}");
                    try
                    {
                        activity?.SetTag("method.name", "{{method.Name}}");
                        activity?.SetTag("class.name", "{{method.ContainingType.Name}}");
                        var result = {{containingTypeDisplay}}.{{method.Name}}({{arguments}});
                        activity?.SetStatus(ActivityStatusCode.Ok);
                        return result;
                    }
                    catch (Exception ex)
                    {
                        activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                        activity?.SetTag("error.type", ex.GetType().Name);
                        activity?.SetTag("error.message", ex.Message);
                        throw;
                    }
            """;
        }
        else
        {
            return 
            $$"""
                    using var activity = _activitySource.StartActivity("{{activityName}}");
                    try
                    {
                        activity?.SetTag("method.name", "{{method.Name}}");
                        activity?.SetTag("class.name", "{{method.ContainingType.Name}}");
                        {{containingTypeDisplay}}.{{method.Name}}({{arguments}});
                        activity?.SetStatus(ActivityStatusCode.Ok);
                    }
                    catch (Exception ex)
                    {
                        activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                        activity?.SetTag("error.type", ex.GetType().Name);
                        activity?.SetTag("error.message", ex.Message);
                        throw;
                    }
            """;
        }
    }

    private static string GenerateAsyncWrapperBody(IMethodSymbol method, string activityName, string arguments)
    {
        var containingTypeDisplay = method.ContainingType.ToDisplayString();

        return 
        $$"""
                using var activity = _activitySource.StartActivity("{{activityName}}");
                try
                {
                    activity?.SetTag("method.name", "{{method.Name}}");
                    activity?.SetTag("class.name", "{{method.ContainingType.Name}}");
                    var result = await {{containingTypeDisplay}}.{{method.Name}}({{arguments}});
                    activity?.SetStatus(ActivityStatusCode.Ok);
                    return result;  
                }
                catch (Exception ex)
                {
                    activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                    activity?.SetTag("error.type", ex.GetType().Name);
                    activity?.SetTag("error.message", ex.Message);
                    throw;
                }
        """;
    }

    private static string GetActivityName(AttributeData attributeData, IMethodSymbol method)
    {
        if (attributeData?.NamedArguments.FirstOrDefault(kvp => kvp.Key == "ActivityName").Value.Value is string activityName)
        {
            return activityName;
        }
        return method.Name;
    }

    private class MethodInfo
    {
        public IMethodSymbol Symbol { get; }
        public MethodDeclarationSyntax Syntax { get; }
        public AttributeData AttributeData { get; }

        public MethodInfo(IMethodSymbol symbol, MethodDeclarationSyntax syntax, AttributeData attributeData)
        {
            Symbol = symbol;
            Syntax = syntax;
            AttributeData = attributeData;
        }
    }

    private const string ActivityAttributeSource = @"// <auto-generated/>
#nullable enable
using System;

namespace ActivitySourceGenerator.Attributes;

/// <summary>
/// Attribute that marks methods for automatic activity tracing.
/// When applied, generates wrapper methods that create activities using ActivitySource,
/// write activity events and errors, and wrap the method's execution.
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
public sealed class ActivityAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the name of the ActivitySource to use for creating activities.
    /// If not specified, uses the containing type's name.
    /// </summary>
    public string? ActivitySourceName { get; set; }

    /// <summary>
    /// Gets or sets the activity name. If not specified, uses the method name.
    /// </summary>
    public string? ActivityName { get; set; }

    /// <summary>
    /// Gets or sets whether to record exceptions as activity errors.
    /// Default is true.
    /// </summary>
    public bool RecordExceptions { get; set; } = true;

    /// <summary>
    /// Gets or sets custom tags to add to the activity.
    /// Format: ""key1=value1;key2=value2""
    /// </summary>
    public string? Tags { get; set; }
}
";
}